# Generated by Django 2.2.4 on 2019-09-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_move', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=500, null=True)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=3)),
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Micro',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'micro',
                'verbose_name_plural': 'micros',
            },
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('x', models.DecimalField(decimal_places=10, max_digits=30)),
                ('y', models.DecimalField(decimal_places=10, max_digits=30)),
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'paradero',
                'verbose_name_plural': 'paraderos',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('puntaje', models.PositiveSmallIntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Conductor')),
            ],
            options={
                'verbose_name': 'valoracion',
                'verbose_name_plural': 'valoraciones',
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('letra', models.CharField(max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Empresa')),
            ],
            options={
                'verbose_name': 'recorrido',
                'verbose_name_plural': 'recorridos',
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Micro')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='PasaPor',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Micro')),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Paradero')),
            ],
        ),
        migrations.AddField(
            model_name='micro',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Recorrido'),
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('inicio', models.PositiveSmallIntegerField()),
                ('fin', models.PositiveSmallIntegerField()),
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Micro')),
            ],
            options={
                'verbose_name': 'itinerario',
                'verbose_name_plural': 'itinerarios',
            },
        ),
        migrations.CreateModel(
            name='Conduce',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Conductor')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_move.Itinerario')),
            ],
        ),
    ]
