# Generated by Django 2.2.5 on 2019-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_move', '0002_auto_20190930_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_de_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
