# Generated by Django 2.2.5 on 2019-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_move', '0003_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
